### ISSUE TITLE
ops-agent-policy not compatible with latest google provider (>6)

### ISSUE THREAD

**Issue by haydenflinner** [terraform-google-modules/terraform-google-cloud-operations#117]
### TL;DR

[This](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/v0.5.1/modules/ops-agent-policy/versions.tf) leads to following pain point when following other commonly available gcloud terraform documentation:
```
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 3.53.0, ~> 6.0, < 6.0.0
```

**Comment by imrannayer** [comment]
@haydenflinner fixed in #116
