### ISSUE TITLE
Error when the OS version is not defined

### ISSUE THREAD

**Issue by sombrabr** [terraform-google-modules/terraform-google-cloud-operations#14]
When applying a Terraform where the `os_types` has only the name of the OS and not the version, an error is thrown:

```
module.cloud_operations_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): ++ gcloud beta compute instances ops-agents policies create ops-agents-policy '--agent-rules=enable-autoupgrade=true,package-state=installed,type=logging,version=current-major;enable-autoupgrade=true,package-state=installed,type=metrics,version=current-major' --os-types=short-name=debian --project=xxx --quiet
module.cloud_operations_agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): ERROR: (gcloud.beta.compute.instances.ops-agents.policies.create) argument --os-types: Key [version] required in dict arg but not provided
```
I don't know how it needs to be changed so when can make `gcloud` cli accept an one property dictionary.

**Comment by bharathkkb** [comment]
@sophieyfang could you take a look at this?

**Comment by philipp-heinrich** [comment]
in the meantime, can you list the variable as "required"? 

https://registry.terraform.io/modules/terraform-google-modules/cloud-operations/google/latest/submodules/agent-policy#os_types-variable

**Comment by zyun-i** [comment]
I had the same problem in my environment, it seems that Python was not installed.

```
module.agent_policy.module.gcloud-upsert.null_resource.run_command[0] (local-exec): /home/test/.terraform/modules/agent_
policy/modules/agent-policy/scripts/script-utils.sh: line 38: python: command not found
```

This module doesn't check the result of the command execution, so it doesn't seem to cause an error on terraform.

**Comment by g-awmalik** [comment]
The version_no is a required field on the os_types list. Closing this issue but feel free to reopen if this persists.
