### ISSUE TITLE
Examples don't run because v2.x google provider is required

### ISSUE THREAD

**Issue by yuryu** [terraform-google-modules/terraform-google-cloud-operations#24]
The examples don't run because they pin to v2.x terraform google provider.

for example, https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/26efc88d929012d17e17e3f86c61f77861eba0b7/examples/agent_policy_simple_example/main.tf#L18

**Comment by morgante** [comment]
Thanks, I think it's a good idea to upgrade the examples to v3.x. PRs welcome.
