### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by black-snow** [terraform-google-modules/terraform-google-cloud-operations#35]
### TL;DR

* add support for Windows
* in the meantime, add a note right [here](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/managing-agent-policies#terraform_integration)

### Detailed design

```markdown
It'd be nice to have this module working on windows as well.

It'd also be nice to state right here https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/managing-agent-policies#terraform_integration that Windows isn't supported atm (or that only macOS and Linux are).
```

**Comment by kanan2u** [comment]
While running the script from https:://registry.terraform.io/modules/terraform-google-modules/cloud-operations/google/latest/submodules/agent-policy, I am getting the below error:
with module.agent_policy.module.gcloud-upsert.data.external.env_override[0],
│   on .terraform\modules\agent_policy.gcloud-upsert\main.tf line 73, in data "external" "env_override":
│   73:   program = ["${path.module}/scripts/check_env.sh"]
Can anyone please suggest on this?

**Comment by crabulik** [comment]
Any updates regarding this issue?
