### ISSUE TITLE
Ops Agent Custom Config Support

### ISSUE THREAD

**Issue by dhurng** [terraform-google-modules/terraform-google-cloud-operations#43]
### TL;DR

It would be great to allow for custom configuration to the ops agent during the install process. 

ex. https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#config-intro

### Terraform Resources

```markdown
It would be great to have this feature in terraform module as well
```

### Detailed design

```markdown
gcloud beta compute instances \
    ops-agents policies create ops-agents-policy-safe-rollout \
    --agent-rules=...
...
    --custom-congig=<either a path to a file that gets loaded into the instance or raw input> 
                    "metrics:
                    receivers:
                        hostmetrics:
                          type: hostmetrics
                             collection_interval: 30s << EOF"
```

**Comment by black-snow** [comment]
For that you'd need to have the instance up and reachable, because you need to modify the yaml - possibly colliding with other modifications you made to it ... We roll out the yaml via ansible.
